import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import type { PrismaClient } from '@prisma/client';
import { createOrder, updateOrderStatus } from '../../lib/orders';
import { recordMovement, updateDispatch } from '../../lib/operations';
import { operationsSummary } from '../../lib/operations-summary';
export async function operationsFlow(db: PrismaClient) {
  const p = await db.producto.create({ data: { nombre: 'QA Operaciones', descripcion: 'Prueba', categoria: 'QA', precioMediaDocena: 30, precioDocena: 60, precioCaja: 720, unidadesPorCaja: 144, stock: 48 } });
  const order = await createOrder(db, { clave: randomUUID(), nombre: 'QA Contabilidad', telefono: '51901111222', items: [{ id: p.id, presentacion: 'docena', cantidad: 1, precio: 60, unidadesPorCaja: 144 }] });
  const movement = (monto: string, tipo = 'COBRO') => ({ clave: randomUUID(), pedidoId: order.id, tipo, monto, concepto: 'Prueba de operación', medio: 'TRANSFERENCIA', referencia: 'QA' });
  await assert.rejects(recordMovement(db, movement('10'), 'QA'), /Confirma/);
  await updateOrderStatus(db, order.id, 'CONFIRMADO');
  const baseline = await operationsSummary(db);
  const same = movement('20');
  const [first, retry] = await Promise.all([recordMovement(db, same, 'QA'), recordMovement(db, same, 'QA')]);
  assert.equal(first.id, retry.id);
  await assert.rejects(recordMovement(db, { ...same, monto: '19' }, 'QA'), /otros datos/);
  await assert.rejects(recordMovement(db, movement('41'), 'QA'), /supera/);
  await assert.rejects(recordMovement(db, movement('1.001'), 'QA'));
  await assert.rejects(recordMovement(db, movement('-1'), 'QA'));
  const concurrent = await Promise.allSettled([recordMovement(db, movement('30'), 'QA'), recordMovement(db, movement('30'), 'QA')]);
  assert.equal(concurrent.filter(r => r.status === 'fulfilled').length, 1);
  const after = await operationsSummary(db);
  assert.ok(baseline.receivable.minus(after.receivable).eq(50));
  assert.ok(after.cash.minus(baseline.cash).eq(50));
  const dispatch = { id: order.id, previous: 'PREPARACION', despacho: 'EN_CAMINO', direccion: 'Av. QA 123', transportista: 'Transporte QA', seguimiento: 'GUIA-01' };
  await assert.rejects(updateDispatch(db, { ...dispatch, direccion: '' }), /dirección/);
  await updateDispatch(db, dispatch);
  await assert.rejects(updateDispatch(db, dispatch), /cambió/);
  await assert.rejects(updateOrderStatus(db, order.id, 'CANCELADO'), /camino/);
  await updateDispatch(db, { ...dispatch, previous: 'EN_CAMINO', despacho: 'PREPARACION' });
  await updateOrderStatus(db, order.id, 'CANCELADO');
  assert.equal((await db.producto.findUniqueOrThrow({ where: { id: p.id } })).stock, 48);
  assert.equal((await db.pedido.findUniqueOrThrow({ where: { id: order.id } })).despacho, 'CANCELADO');
  assert.ok((await operationsSummary(db)).refundable.minus(baseline.refundable).eq(50));
  await assert.rejects(recordMovement(db, movement('1'), 'QA'), /Confirma/);
  await assert.rejects(recordMovement(db, movement('51', 'DEVOLUCION'), 'QA'), /supera/);
  const refunds = await Promise.allSettled([recordMovement(db, movement('40', 'DEVOLUCION'), 'QA'), recordMovement(db, movement('40', 'DEVOLUCION'), 'QA')]);
  assert.equal(refunds.filter(r => r.status === 'fulfilled').length, 1);
  await recordMovement(db, movement('10', 'DEVOLUCION'), 'QA');
  await recordMovement(db, { ...movement('5', 'GASTO'), pedidoId: '' }, 'QA');
  assert.ok((await operationsSummary(db)).refundable.eq(baseline.refundable));
  assert.ok((await operationsSummary(db)).cash.eq(baseline.cash.minus(5)));
  const delivered = await createOrder(db, { clave: randomUUID(), nombre: 'QA Entrega', telefono: '51901111223', items: [{ id: p.id, presentacion: 'docena', cantidad: 1, precio: 60, unidadesPorCaja: 144 }] });
  await updateOrderStatus(db, delivered.id, 'CONFIRMADO');
  await updateDispatch(db, { ...dispatch, id: delivered.id });
  await updateOrderStatus(db, delivered.id, 'ENTREGADO');
  const result = await db.pedido.findUniqueOrThrow({ where: { id: delivered.id } });
  assert.equal(result.despacho, 'ENTREGADO');
  assert.ok(result.entregadoAt);
  await assert.rejects(updateDispatch(db, { ...dispatch, id: delivered.id, previous: 'EN_CAMINO' }), /confirmados/);
  console.log('Contabilidad y logística: cobros concurrentes, reintentos, devoluciones, saldos, despachos y entrega verificados.');
}
