'use client';
import { useEffect, useState } from 'react';
import Image from 'next/image';
import Link from 'next/link';
import { ArrowLeft, ArrowRight, HatGlasses, Minus, Plus, ShoppingBag, Trash2, MessageCircle, Undo2 } from 'lucide-react';
import { useCart } from '@/lib/cart';
import { CartItem, itemKey, money, presentationLabel, subtotal, whatsappUrl } from '@/lib/commerce';
import { isProductImage } from '@/lib/validation';
export function Cart({ whatsapp }: { whatsapp: string }) {
  const { items, quantity, remove, clear, add } = useCart();
  const [ready, setReady] = useState(false);
  const [removed, setRemoved] = useState<CartItem[]>([]);
  useEffect(() => { Promise.resolve(useCart.persist.rehydrate()).then(() => setReady(true)); }, []);
  if (!ready) return <p className="py-12 text-stone-500" role="status">Cargando tu pedido…</p>;
  const href = whatsappUrl(whatsapp, items);
  const packages = items.reduce((sum, i) => sum + i.cantidad, 0);
  const units = items.reduce((sum, i) => sum + i.cantidad * (i.presentacion === 'mediaDocena' ? 6 : i.presentacion === 'docena' ? 12 : i.unidadesPorCaja), 0);
  return <>
    {removed.length > 0 && <div role="status" className="mt-6 flex flex-wrap items-center justify-between gap-3 rounded-xl border border-accent/20 bg-[#f3eee5] px-4 py-2 text-sm"><span>{removed.length === 1 ? `${removed[0].nombre} se quitó del pedido.` : 'Se vació tu pedido.'}</span><button className="inline-flex min-h-11 items-center gap-2 font-semibold underline underline-offset-4" onClick={() => { removed.forEach(add); setRemoved([]); }}><Undo2 size={16} />Deshacer</button></div>}
    {!items.length ? <div className="mt-8 rounded-3xl border border-ink/10 bg-[#f1efe8] px-6 py-14 text-center sm:py-20"><ShoppingBag className="mx-auto mb-6 text-accent" size={40} strokeWidth={1} /><h2 className="font-serif text-3xl">Tu próximo pedido empieza aquí</h2><p className="my-4 text-sm leading-7 text-stone-500">Explora el catálogo y agrega tus favoritos.<br />Puedes comprar desde media docena.</p><Link href="/#catalogo" className="btn">Ver catálogo <ArrowRight size={17} /></Link></div> : <div className="mt-8 grid items-start gap-5 lg:grid-cols-[minmax(0,1fr)_360px]">
      <div><div className="mb-4 flex items-center justify-between"><p className="text-xs text-stone-500">Tu selección · {items.length} {items.length === 1 ? 'presentación' : 'presentaciones'}</p><button className="min-h-11 text-xs text-stone-500 underline underline-offset-4" onClick={() => { setRemoved(items); clear(); }}>Vaciar carrito</button></div><div className="space-y-4">{items.map(i => <article key={itemKey(i)} className="card p-4 sm:p-5">
        <div className="flex items-start gap-3 sm:gap-4"><Link href={`/producto/${i.id}`} aria-label={`Ver ${i.nombre}`} className="relative flex h-20 w-16 shrink-0 items-center justify-center overflow-hidden rounded-xl bg-[#f1efe8] sm:h-24 sm:w-20">{isProductImage(i.imagen) ? <Image src={i.imagen} alt="" fill sizes="80px" className="object-contain p-2" /> : <HatGlasses size={27} strokeWidth={1} className="text-accent" />}</Link><div className="min-w-0 flex-1"><Link href={`/producto/${i.id}`} className="break-words text-sm font-semibold hover:underline sm:text-base">{i.nombre}</Link><p className="mt-2 text-xs leading-5 text-stone-500">{presentationLabel(i.presentacion, i.unidadesPorCaja)}</p><p className="mt-2 text-xs">{money(i.precio)} <span className="text-stone-500">por paquete</span></p></div><button aria-label={`Eliminar ${i.nombre}, ${i.presentacion}`} onClick={() => { setRemoved([i]); remove(itemKey(i)); }} className="flex h-11 w-11 shrink-0 items-center justify-center rounded-full text-stone-500 transition hover:bg-red-50 hover:text-red-700"><Trash2 size={17} /></button></div>
        <div className="mt-5 flex flex-wrap items-end justify-between gap-3 border-t border-stone-100 pt-4"><div><p className="mb-2 text-[11px] text-stone-500">Paquetes</p><div className="inline-flex items-center rounded-full border border-ink/15 p-1"><button className="quantity-button" aria-label={`Reducir cantidad de ${i.nombre}, ${i.presentacion}`} disabled={i.cantidad === 1} onClick={() => quantity(itemKey(i), i.cantidad - 1)}><Minus size={15} /></button><input aria-label={`Cantidad de ${i.nombre}, ${i.presentacion}`} className="quantity-input" type="number" min={1} max={999} value={i.cantidad} onChange={e => quantity(itemKey(i), Number(e.target.value))} /><button className="quantity-button" aria-label={`Aumentar cantidad de ${i.nombre}, ${i.presentacion}`} disabled={i.cantidad === 999} onClick={() => quantity(itemKey(i), i.cantidad + 1)}><Plus size={15} /></button></div></div><strong className="pb-3 text-lg tabular-nums">{money(subtotal(i) / 100)}</strong></div>
      </article>)}</div><Link href="/#catalogo" className="mt-5 inline-flex min-h-11 items-center gap-2 text-sm"><ArrowLeft size={16} />Seguir comprando</Link></div>
      <aside className="overflow-hidden rounded-3xl border border-ink/10 bg-[#f1efe8] p-6 lg:sticky lg:top-32"><h2 className="text-xl font-medium tracking-tight">Resumen del pedido</h2><dl className="mt-6 space-y-3 text-sm"><div className="flex justify-between"><dt className="text-stone-600">Paquetes</dt><dd>{packages}</dd></div><div className="flex justify-between"><dt className="text-stone-600">Unidades</dt><dd>{units}</dd></div><div className="flex justify-between"><dt className="text-stone-600">Envío</dt><dd>Por coordinar</dd></div></dl><div className="my-6 flex flex-wrap items-center justify-between gap-2 border-y border-ink/10 py-5"><span className="text-sm font-medium">Total de productos</span><strong className="text-2xl tabular-nums">{money(items.reduce((sum, i) => sum + subtotal(i), 0) / 100)}</strong></div>{href ? <a href={href} className="btn w-full"><MessageCircle size={18} className="shrink-0" /><span>Enviar pedido por WhatsApp</span></a> : <p role="status" className="text-sm text-amber-800">El canal de pedidos aún no está disponible. Inténtalo más tarde.</p>}<p className="mt-5 text-xs leading-6 text-stone-600">Confirma disponibilidad, pago y envío con nosotros por WhatsApp.</p></aside>
    </div>}
  </>;
}
