import Image from 'next/image';
import Link from 'next/link';
import { ArrowUpRight, Eye, EyeOff, HatGlasses, Package, Plus, Search } from 'lucide-react';
import { db } from '@/lib/db';
import { requireAdmin } from '@/lib/auth';
import { money } from '@/lib/commerce';
import { ProductControls } from '@/components/product-controls';
export default async function ProductsPage({ searchParams }: { searchParams: Promise<{ q?: string; estado?: string }> }) {
  await requireAdmin();
  const products = await db.producto.findMany({ orderBy: { createdAt: 'desc' }, include: { imagenes: { orderBy: { orden: 'asc' }, take: 1 } } });
  const params = await searchParams;
  const query = typeof params.q === 'string' ? params.q.trim().slice(0, 100) : '';
  const status = params.estado === 'publicados' || params.estado === 'ocultos' ? params.estado : '';
  const normalize = (value: string) => value.normalize('NFD').replace(/[\u0300-\u036f]/g, '').toLocaleLowerCase('es');
  const filtered = products.filter(p => (!query || normalize(`${p.nombre} ${p.categoria}`).includes(normalize(query))) && (!status || p.activo === (status === 'publicados')));
  const active = products.filter(p => p.activo).length;
  return <>
    <div className="mb-8 flex flex-wrap items-end justify-between gap-5"><div><p className="eyebrow text-accent">Tu tienda, al día</p><h1 className="mt-3 text-4xl font-medium tracking-tight sm:text-5xl">Tus productos<span className="text-accent">.</span></h1><p className="mt-3 text-sm leading-6 text-stone-500">Todo lo que necesitas para dar vida a tu colección.</p></div><Link href="/admin/productos/nuevo" className="btn"><Plus size={18} />Nuevo producto</Link></div>
    <dl className="mb-9 grid grid-cols-3 gap-2 sm:gap-4">
      {[{ label: 'Productos', value: products.length, Icon: Package }, { label: 'Publicados', value: active, Icon: Eye }, { label: 'Ocultos', value: products.length - active, Icon: EyeOff }].map(({ label, value, Icon }) => <div key={label} className="card p-4 sm:p-6"><dt className="flex items-center justify-between gap-2 text-[11px] text-stone-500 sm:text-sm">{label}<Icon className="hidden text-accent sm:block" size={18} /></dt><dd className="mt-3 text-3xl font-medium tracking-tight sm:text-4xl">{value.toString().padStart(2, '0')}</dd></div>)}
    </dl>
    {products.length > 0 && <form action="/admin/productos" role="search" aria-label="Buscar en administración" className="mb-6 flex flex-wrap items-end gap-3"><label className="min-w-0 flex-1 text-xs font-medium">Buscar producto<div className="relative mt-2"><Search size={17} className="absolute left-4 top-4 text-stone-400" /><input type="search" name="q" maxLength={100} defaultValue={query} placeholder="Nombre o categoría" className="field pl-11" /></div></label><label className="text-xs font-medium">Estado<select name="estado" defaultValue={status} className="field mt-2"><option value="">Todos</option><option value="publicados">Publicados</option><option value="ocultos">Ocultos</option></select></label><button className="btn-secondary">Filtrar</button>{(query || status) && <Link href="/admin/productos" className="inline-flex min-h-12 items-center text-xs underline underline-offset-4">Limpiar filtros</Link>}</form>}
    {products.length > 0 && <p className="mb-4 text-xs text-stone-500" role="status">{filtered.length} de {products.length} productos</p>}
    {products.length && !filtered.length ? <div className="card px-6 py-12 text-center"><Search size={28} className="mx-auto mb-4 text-accent" /><h2 className="text-xl font-medium">No encontramos ese producto</h2><p className="mt-3 text-sm text-stone-500">Prueba otro nombre o cambia el estado seleccionado.</p><Link href="/admin/productos" className="btn-secondary mt-6">Mostrar todos</Link></div> : products.length ? <div className="space-y-3">{filtered.map(p => <article key={p.id} className="card flex flex-col gap-5 p-4 sm:p-5 xl:flex-row xl:items-center xl:justify-between">
      <div className="flex min-w-0 items-center gap-4"><div className="relative flex h-20 w-20 shrink-0 items-center justify-center overflow-hidden rounded-xl bg-[#f1efe8]">{p.imagenes[0] ? <Image src={p.imagenes[0].url} alt={p.nombre} fill sizes="80px" className="object-contain p-2" /> : <HatGlasses size={30} strokeWidth={1} className="text-accent" />}</div><div className="min-w-0"><p className="eyebrow text-[9px]">{p.categoria}</p><h2 className="mt-1 break-words text-base font-semibold">{p.nombre}</h2><p className="mt-2 text-xs text-stone-500">½ docena <span className="font-medium text-ink">{money(Number(p.precioMediaDocena))}</span></p></div></div>
      <div className="flex flex-wrap items-center gap-4 border-t border-stone-100 pt-4 xl:shrink-0 xl:border-0 xl:pt-0"><span className={`inline-flex items-center gap-1.5 rounded-full px-3 py-1.5 text-[11px] font-medium ${p.activo ? 'bg-emerald-50 text-emerald-800' : 'bg-stone-100 text-stone-600'}`}><span className={`h-1.5 w-1.5 rounded-full ${p.activo ? 'bg-emerald-600' : 'bg-stone-400'}`} />{p.activo ? 'Publicado' : 'Oculto'}</span><ProductControls id={p.id} active={p.activo} /></div>
    </article>)}</div> : <div className="grid overflow-hidden rounded-3xl border border-ink/10 bg-[#f1efe8] md:grid-cols-[1.4fr_1fr]">
      <div className="p-7 sm:p-10"><span className="mb-6 flex h-14 w-14 items-center justify-center rounded-2xl border border-accent/20 bg-paper"><HatGlasses size={28} strokeWidth={1.25} className="text-accent" /></span><p className="eyebrow">Empieza con tu favorito</p><h2 className="mt-3 max-w-md text-3xl font-medium leading-tight tracking-tight">Tu colección empieza<br />con el primer producto.</h2><p className="mt-4 max-w-md text-sm leading-7 text-stone-600">Agrega sus fotos, elige una categoría y define los precios por presentación. Tú decides cuándo publicarlo.</p><Link href="/admin/productos/nuevo" className="mt-7 inline-flex min-h-12 items-center gap-3 border-b border-ink text-sm font-semibold">Crear mi primer producto <ArrowUpRight size={18} /></Link></div>
      <div className="flex flex-col justify-center gap-6 border-t border-ink/10 p-7 sm:p-10 md:border-l md:border-t-0">{[{title:'Una buena foto',text:'Muestra los detalles y los colores del modelo.'},{title:'Precios claros',text:'Media docena, docena y caja completa.'},{title:'Listo para compartir',text:'Activa el producto para mostrarlo en tu tienda.'}].map((item,i)=><div key={item.title} className="flex gap-4"><span className="pt-0.5 font-serif text-2xl italic text-accent">0{i+1}</span><div><h3 className="text-sm font-semibold">{item.title}</h3><p className="mt-1 text-xs leading-6 text-stone-500">{item.text}</p></div></div>)}</div>
    </div>}
  </>;
}
